#!/bin/bash

set -euo pipefail

mkdir -p slurm_logs

IMAGENET_DATA_ROOT=${IMAGENET_DATA_ROOT:-/project_gpfs/bata0/bjin0/imagenet64_official_verified_20260505}
IMAGENET_TRAIN_DIR=${IMAGENET_TRAIN_DIR:-${IMAGENET_DATA_ROOT}/train}
IMAGENET_VAL_DIR=${IMAGENET_VAL_DIR:-${IMAGENET_DATA_ROOT}/val}
EXPERIMENT=${EXPERIMENT:-linear_simple}

# Keep this short: enough to load data, run forward/backward, log, and exit.
IMAGENET_BATCH_SIZE=${IMAGENET_BATCH_SIZE:-16}
IMAGENET_MICROBATCH=${IMAGENET_MICROBATCH:-4}
IMAGENET_USE_FP16=${IMAGENET_USE_FP16:-True}
IMAGENET_LR_ANNEAL_STEPS=${IMAGENET_LR_ANNEAL_STEPS:-20}
IMAGENET_LOG_INTERVAL=${IMAGENET_LOG_INTERVAL:-1}
IMAGENET_SAVE_INTERVAL=${IMAGENET_SAVE_INTERVAL:-100000}

echo "Submitting ImageNet-64 smoke training job with:"
echo "  EXPERIMENT=$EXPERIMENT"
echo "  IMAGENET_DATA_ROOT=$IMAGENET_DATA_ROOT"
echo "  IMAGENET_TRAIN_DIR=$IMAGENET_TRAIN_DIR"
echo "  IMAGENET_VAL_DIR=$IMAGENET_VAL_DIR"
echo "  IMAGENET_BATCH_SIZE=$IMAGENET_BATCH_SIZE"
echo "  IMAGENET_MICROBATCH=$IMAGENET_MICROBATCH"
echo "  IMAGENET_LR_ANNEAL_STEPS=$IMAGENET_LR_ANNEAL_STEPS"

sbatch \
  --time=02:00:00 \
  --export=ALL,EXPERIMENT="$EXPERIMENT",IMAGENET_DATA_ROOT="$IMAGENET_DATA_ROOT",IMAGENET_TRAIN_DIR="$IMAGENET_TRAIN_DIR",IMAGENET_VAL_DIR="$IMAGENET_VAL_DIR",IMAGENET_BATCH_SIZE="$IMAGENET_BATCH_SIZE",IMAGENET_MICROBATCH="$IMAGENET_MICROBATCH",IMAGENET_USE_FP16="$IMAGENET_USE_FP16",IMAGENET_LR_ANNEAL_STEPS="$IMAGENET_LR_ANNEAL_STEPS",IMAGENET_LOG_INTERVAL="$IMAGENET_LOG_INTERVAL",IMAGENET_SAVE_INTERVAL="$IMAGENET_SAVE_INTERVAL" \
  --job-name="im64_smoke_${EXPERIMENT}" \
  --output="slurm_logs/im64_smoke_${EXPERIMENT}_%j.out" \
  --error="slurm_logs/im64_smoke_${EXPERIMENT}_%j.err" \
  train_imagenet64_no_mpi.slurm
