#!/usr/bin/env python3
"""
Compute FID for an NPZ of samples (arr_0) against a precomputed stats file.

This is designed for SLURM evaluation jobs (GPU available), so that each eval job
produces a single numeric FID result that aggregation can read without doing any
heavy work on the login node.
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

import numpy as np
from PIL import Image


def _run(cmd: list[str]) -> str:
    proc = subprocess.run(cmd, capture_output=True, text=True)
    if proc.returncode != 0:
        raise RuntimeError(
            "Command failed:\n"
            f"  {' '.join(cmd)}\n\n"
            f"stdout:\n{proc.stdout}\n\n"
            f"stderr:\n{proc.stderr}\n"
        )
    return proc.stdout + proc.stderr


def _parse_fid(output: str) -> float:
    # pytorch-fid prints: "FID: XX.XXXX"
    m = re.search(r"FID:\s*([0-9]+(?:\.[0-9]+)?)", output)
    if not m:
        raise ValueError(f"Could not parse FID from pytorch-fid output:\n{output}")
    return float(m.group(1))


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--samples_npz", required=True, help="Path to samples_*.npz")
    ap.add_argument(
        "--stats_npz",
        required=True,
        help="Path to stats .npz generated by pytorch-fid --save-stats",
    )
    ap.add_argument(
        "--device",
        default="cuda",
        help="pytorch-fid device: cuda or cpu (default: cuda)",
    )
    ap.add_argument(
        "--tmp_root",
        default=None,
        help="Optional directory to place temp images under (e.g. /project_gpfs/$USER).",
    )
    ap.add_argument(
        "--output_txt",
        default=None,
        help="Optional output file to write the numeric FID into.",
    )
    args = ap.parse_args()

    samples_npz = Path(args.samples_npz)
    stats_npz = Path(args.stats_npz)
    if not samples_npz.is_file():
        raise FileNotFoundError(samples_npz)
    if not stats_npz.is_file():
        raise FileNotFoundError(stats_npz)

    # Load samples.
    data = np.load(samples_npz)
    if "arr_0" not in data:
        raise KeyError(f"{samples_npz} does not contain key 'arr_0'")
    images = data["arr_0"]
    data.close()

    if images.ndim != 4 or images.shape[-1] != 3:
        raise ValueError(f"Expected NHWC uint8 images, got shape={images.shape}")
    if images.dtype != np.uint8:
        raise ValueError(
            f"Expected uint8 samples in arr_0, got dtype={images.dtype}. "
            "Refusing to cast silently, since that can hide NaNs/Inf and produce misleading FIDs."
        )

    # Create temp directory for images.
    tmp_kwargs = {}
    if args.tmp_root:
        tmp_root = Path(args.tmp_root)
        tmp_root.mkdir(parents=True, exist_ok=True)
        tmp_kwargs["dir"] = str(tmp_root)

    with tempfile.TemporaryDirectory(prefix="fid_images_", **tmp_kwargs) as tmp_dir:
        img_dir = Path(tmp_dir)

        # Write PNGs (pytorch-fid expects image files).
        for i, img_array in enumerate(images):
            img = Image.fromarray(img_array.astype(np.uint8), "RGB")
            img.save(img_dir / f"sample_{i:05d}.png")

        # Compute FID vs precomputed stats.
        out = _run(
            [
                sys.executable,
                "-m",
                "pytorch_fid",
                str(img_dir),
                str(stats_npz),
                "--device",
                args.device,
            ]
        )
        fid = _parse_fid(out)

    if args.output_txt:
        out_path = Path(args.output_txt)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(f"{fid:.6f}\n")

    print(f"FID: {fid:.6f}")


if __name__ == "__main__":
    main()


